import bmw1 from "../assets/bmw1.png";
import bmw2 from "../assets/bmw2.png";
import bmw3 from "../assets/bmw3.png";
import bmw4 from "../assets/bmw4.png";
import bmw5 from "../assets/bmw5.png";
import bmw6 from "../assets/bmw6.png";
import bmw7 from "../assets/bmw7.png";

export const productos = [
  {
    item_id: 1,
    img: [bmw1, bmw2, bmw3, bmw4, bmw5, bmw6, bmw7],
    card_brand: "BMW",
    name: "BMW Serie 3 2.0 320i Sedan Executive",
    description: ["Bmw 320i LCI 2016 full equipo 1 mano",
                  "SERVICE oficiales\nMotor B48 línea nueva",
                  "Discos y pastillas recién cambiados",
                  "Neumáticos con 3000 km RUN FLAT OEM",
                  "Rodado 18 bimedida opcional",
                  "CUERO",
                  "Techo de vidrio",
                  "Faros full led delanteros y traseros",
                  "Pantalla grande con GPS y disco rígido",
                  "CAR PLAY inalambrico",
                  "Asistente de estacionamiento delantero y trasero",
                  "El mejor del mercado!"],
    characteristics: ["Control de la velocidad de crucero", "Automático", "Bluetoth", "Aire acondicionado"],
    price_per_hour: 25000,
    category_id: "Premium",
  },
  {
    item_id: 2,
    img: [bmw1, bmw2, bmw3, bmw4, bmw5, bmw6, bmw7],
    card_brand: "BMW",
    name: "BMW Serie 3 2.0 320i Sedan Executive",
    description: ["Bmw 320i LCI 2016 full equipo 1 mano",
                  "SERVICE oficiales\nMotor B48 línea nueva",
                  "Discos y pastillas recién cambiados",
                  "Neumáticos con 3000 km RUN FLAT OEM",
                  "Rodado 18 bimedida opcional",
                  "CUERO",
                  "Techo de vidrio",
                  "Faros full led delanteros y traseros",
                  "Pantalla grande con GPS y disco rígido",
                  "CAR PLAY inalambrico",
                  "Asistente de estacionamiento delantero y trasero",
                  "El mejor del mercado!"],
    characteristics: ["Control de la velocidad de crucero", "Automático", "Bluetoth", "Aire acondicionado"],
    price_per_hour: 25000,
    category_id: "",
  },
  {
    item_id: 3,
    img: [bmw1, bmw2, bmw3, bmw4, bmw5, bmw6, bmw7],
    card_brand: "BMW",
    name: "BMW Serie 3 2.0 320i Sedan Executive",
    description: ["Bmw 320i LCI 2016 full equipo 1 mano",
                  "SERVICE oficiales\nMotor B48 línea nueva",
                  "Discos y pastillas recién cambiados",
                  "Neumáticos con 3000 km RUN FLAT OEM",
                  "Rodado 18 bimedida opcional",
                  "CUERO",
                  "Techo de vidrio",
                  "Faros full led delanteros y traseros",
                  "Pantalla grande con GPS y disco rígido",
                  "CAR PLAY inalambrico",
                  "Asistente de estacionamiento delantero y trasero",
                  "El mejor del mercado!"],
    characteristics: ["Control de la velocidad de crucero", "Automático", "Bluetoth", "Aire acondicionado"],
    price_per_hour: 25000,
    category_id: "",
  },
  {
    item_id: 4,
    img: [bmw1, bmw2, bmw3, bmw4, bmw5, bmw6, bmw7],
    card_brand: "BMW",
    name: "BMW Serie 3 2.0 320i Sedan Executive",
    description: ["Bmw 320i LCI 2016 full equipo 1 mano",
                  "SERVICE oficiales\nMotor B48 línea nueva",
                  "Discos y pastillas recién cambiados",
                  "Neumáticos con 3000 km RUN FLAT OEM",
                  "Rodado 18 bimedida opcional",
                  "CUERO",
                  "Techo de vidrio",
                  "Faros full led delanteros y traseros",
                  "Pantalla grande con GPS y disco rígido",
                  "CAR PLAY inalambrico",
                  "Asistente de estacionamiento delantero y trasero",
                  "El mejor del mercado!"],
    characteristics: ["Control de la velocidad de crucero", "Automático", "Bluetoth", "Aire acondicionado"],
    price_per_hour: 25000,
    category_id: "",
  },
  {
    item_id: 5,
    img: [bmw1, bmw2, bmw3, bmw4, bmw5, bmw6, bmw7],
    card_brand: "BMW",
    name: "BMW Serie 3 2.0 320i Sedan Executive",
    description: ["Bmw 320i LCI 2016 full equipo 1 mano",
                  "SERVICE oficiales\nMotor B48 línea nueva",
                  "Discos y pastillas recién cambiados",
                  "Neumáticos con 3000 km RUN FLAT OEM",
                  "Rodado 18 bimedida opcional",
                  "CUERO",
                  "Techo de vidrio",
                  "Faros full led delanteros y traseros",
                  "Pantalla grande con GPS y disco rígido",
                  "CAR PLAY inalambrico",
                  "Asistente de estacionamiento delantero y trasero",
                  "El mejor del mercado!"],
    characteristics: ["Control de la velocidad de crucero", "Automático", "Bluetoth", "Aire acondicionado"],
    price_per_hour: 25,
    category_id: "",
  },
  {
    item_id: 6,
    img: [bmw1, bmw2, bmw3, bmw4, bmw5, bmw6, bmw7],
    card_brand: "BMW",
    name: "BMW Serie 3 2.0 320i Sedan Executive",
    description: ["Bmw 320i LCI 2016 full equipo 1 mano",
                  "SERVICE oficiales\nMotor B48 línea nueva",
                  "Discos y pastillas recién cambiados",
                  "Neumáticos con 3000 km RUN FLAT OEM",
                  "Rodado 18 bimedida opcional",
                  "CUERO",
                  "Techo de vidrio",
                  "Faros full led delanteros y traseros",
                  "Pantalla grande con GPS y disco rígido",
                  "CAR PLAY inalambrico",
                  "Asistente de estacionamiento delantero y trasero",
                  "El mejor del mercado!"],
    characteristics: ["Control de la velocidad de crucero", "Automático", "Bluetoth", "Aire acondicionado"],
    price_per_hour: 25,
    category_id: "",
  },
  {
    item_id: 7,
    img: [bmw1, bmw2, bmw3, bmw4, bmw5, bmw6, bmw7],
    card_brand: "BMW",
    name: "BMW Serie 3 2.0 320i Sedan Executive",
    description: ["Bmw 320i LCI 2016 full equipo 1 mano",
                  "SERVICE oficiales\nMotor B48 línea nueva",
                  "Discos y pastillas recién cambiados",
                  "Neumáticos con 3000 km RUN FLAT OEM",
                  "Rodado 18 bimedida opcional",
                  "CUERO",
                  "Techo de vidrio",
                  "Faros full led delanteros y traseros",
                  "Pantalla grande con GPS y disco rígido",
                  "CAR PLAY inalambrico",
                  "Asistente de estacionamiento delantero y trasero",
                  "El mejor del mercado!"],
    characteristics: ["Control de la velocidad de crucero", "Automático", "Bluetoth", "Aire acondicionado"],
    price_per_hour: 25,
    category_id: "",
  },
  {
    item_id: 8,
    img: [bmw1, bmw2, bmw3, bmw4, bmw5, bmw6, bmw7],
    card_brand: "BMW",
    name: "BMW Serie 3 2.0 320i Sedan Executive",
    description: ["Bmw 320i LCI 2016 full equipo 1 mano",
                  "SERVICE oficiales\nMotor B48 línea nueva",
                  "Discos y pastillas recién cambiados",
                  "Neumáticos con 3000 km RUN FLAT OEM",
                  "Rodado 18 bimedida opcional",
                  "CUERO",
                  "Techo de vidrio",
                  "Faros full led delanteros y traseros",
                  "Pantalla grande con GPS y disco rígido",
                  "CAR PLAY inalambrico",
                  "Asistente de estacionamiento delantero y trasero",
                  "El mejor del mercado!"],
    characteristics: ["Control de la velocidad de crucero", "Automático", "Bluetoth", "Aire acondicionado"],
    price_per_hour: 25,
    category_id: "",
  },
  {
    item_id: 9,
    img: [bmw1, bmw2, bmw3, bmw4, bmw5, bmw6, bmw7],
    card_brand: "BMW",
    name: "BMW Serie 3 2.0 320i Sedan Executive",
    description: ["Bmw 320i LCI 2016 full equipo 1 mano",
                  "SERVICE oficiales\nMotor B48 línea nueva",
                  "Discos y pastillas recién cambiados",
                  "Neumáticos con 3000 km RUN FLAT OEM",
                  "Rodado 18 bimedida opcional",
                  "CUERO",
                  "Techo de vidrio",
                  "Faros full led delanteros y traseros",
                  "Pantalla grande con GPS y disco rígido",
                  "CAR PLAY inalambrico",
                  "Asistente de estacionamiento delantero y trasero",
                  "El mejor del mercado!"],
    characteristics: ["Control de la velocidad de crucero", "Automático", "Bluetoth", "Aire acondicionado"],
    price_per_hour: 25,
    category_id: "",
  },
  {
    item_id: 10,
    img: [bmw1, bmw2, bmw3, bmw4, bmw5, bmw6, bmw7],
    card_brand: "BMW",
    name: "BMW Serie 3 2.0 320i Sedan Executive",
    description: ["Bmw 320i LCI 2016 full equipo 1 mano",
                  "SERVICE oficiales\nMotor B48 línea nueva",
                  "Discos y pastillas recién cambiados",
                  "Neumáticos con 3000 km RUN FLAT OEM",
                  "Rodado 18 bimedida opcional",
                  "CUERO",
                  "Techo de vidrio",
                  "Faros full led delanteros y traseros",
                  "Pantalla grande con GPS y disco rígido",
                  "CAR PLAY inalambrico",
                  "Asistente de estacionamiento delantero y trasero",
                  "El mejor del mercado!"],
    characteristics: ["Control de la velocidad de crucero", "Automático", "Bluetoth", "Aire acondicionado"],
    price_per_hour: 25,
    category_id: "",
  },
  {
    item_id: 11,
    img: [bmw1, bmw2, bmw3, bmw4, bmw5, bmw6, bmw7],
    card_brand: "BMW",
    name: "BMW Serie 3 2.0 320i Sedan Executive",
    description: ["Bmw 320i LCI 2016 full equipo 1 mano",
                  "SERVICE oficiales\nMotor B48 línea nueva",
                  "Discos y pastillas recién cambiados",
                  "Neumáticos con 3000 km RUN FLAT OEM",
                  "Rodado 18 bimedida opcional",
                  "CUERO",
                  "Techo de vidrio",
                  "Faros full led delanteros y traseros",
                  "Pantalla grande con GPS y disco rígido",
                  "CAR PLAY inalambrico",
                  "Asistente de estacionamiento delantero y trasero",
                  "El mejor del mercado!"],
    characteristics: ["Control de la velocidad de crucero", "Automático", "Bluetoth", "Aire acondicionado"],
    price_per_hour: 25,
    category_id: "",
  },
  {
    item_id: 12,
    img: [bmw1, bmw2, bmw3, bmw4, bmw5, bmw6, bmw7],
    card_brand: "BMW",
    name: "BMW Serie 3 2.0 320i Sedan Executive",
    description: ["Bmw 320i LCI 2016 full equipo 1 mano",
                  "SERVICE oficiales\nMotor B48 línea nueva",
                  "Discos y pastillas recién cambiados",
                  "Neumáticos con 3000 km RUN FLAT OEM",
                  "Rodado 18 bimedida opcional",
                  "CUERO",
                  "Techo de vidrio",
                  "Faros full led delanteros y traseros",
                  "Pantalla grande con GPS y disco rígido",
                  "CAR PLAY inalambrico",
                  "Asistente de estacionamiento delantero y trasero",
                  "El mejor del mercado!"],
    characteristics: ["Control de la velocidad de crucero", "Automático", "Bluetoth", "Aire acondicionado"],
    price_per_hour: 25,
    category_id: "",
  },
  {
    item_id: 13,
    img: [bmw1, bmw2, bmw3, bmw4, bmw5, bmw6, bmw7],
    card_brand: "BMW",
    name: "BMW Serie 3 2.0 320i Sedan Executive",
    description: ["Bmw 320i LCI 2016 full equipo 1 mano",
                  "SERVICE oficiales\nMotor B48 línea nueva",
                  "Discos y pastillas recién cambiados",
                  "Neumáticos con 3000 km RUN FLAT OEM",
                  "Rodado 18 bimedida opcional",
                  "CUERO",
                  "Techo de vidrio",
                  "Faros full led delanteros y traseros",
                  "Pantalla grande con GPS y disco rígido",
                  "CAR PLAY inalambrico",
                  "Asistente de estacionamiento delantero y trasero",
                  "El mejor del mercado!"],
    characteristics: ["Control de la velocidad de crucero", "Automático", "Bluetoth", "Aire acondicionado"],
    price_per_hour: 25,
    category_id: "",
  },
  {
    item_id: 14,
    img: [bmw1, bmw2, bmw3, bmw4, bmw5, bmw6, bmw7],
    card_brand: "BMW",
    name: "BMW Serie 3 2.0 320i Sedan Executive",
    description: ["Bmw 320i LCI 2016 full equipo 1 mano",
                  "SERVICE oficiales\nMotor B48 línea nueva",
                  "Discos y pastillas recién cambiados",
                  "Neumáticos con 3000 km RUN FLAT OEM",
                  "Rodado 18 bimedida opcional",
                  "CUERO",
                  "Techo de vidrio",
                  "Faros full led delanteros y traseros",
                  "Pantalla grande con GPS y disco rígido",
                  "CAR PLAY inalambrico",
                  "Asistente de estacionamiento delantero y trasero",
                  "El mejor del mercado!"],
    characteristics: ["Control de la velocidad de crucero", "Automático", "Bluetoth", "Aire acondicionado"],
    price_per_hour: 25,
    category_id: "",
  },
  {
    item_id: 15,
    img: [bmw1, bmw2, bmw3, bmw4, bmw5, bmw6, bmw7],
    card_brand: "BMW",
    name: "BMW Serie 3 2.0 320i Sedan Executive",
    description: ["Bmw 320i LCI 2016 full equipo 1 mano",
                  "SERVICE oficiales\nMotor B48 línea nueva",
                  "Discos y pastillas recién cambiados",
                  "Neumáticos con 3000 km RUN FLAT OEM",
                  "Rodado 18 bimedida opcional",
                  "CUERO",
                  "Techo de vidrio",
                  "Faros full led delanteros y traseros",
                  "Pantalla grande con GPS y disco rígido",
                  "CAR PLAY inalambrico",
                  "Asistente de estacionamiento delantero y trasero",
                  "El mejor del mercado!"],
    characteristics: ["Control de la velocidad de crucero", "Automático", "Bluetoth", "Aire acondicionado"],
    price_per_hour: 25,
    category_id: "",
  },
];